import type { Metadata } from "next";
import { Inter } from "next/font/google";
import  { Toaster } from 'react-hot-toast';

import { GoogleOAuthProvider } from '@react-oauth/google';
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   <GoogleOAuthProvider clientId="326114814668-q90tmt7ncb55llipnobjred7t4j82sop.apps.googleusercontent.com">
     <html lang="en">
      <body className={inter.className}>{children}</body>
      <Toaster/>
    </html>
   
   </GoogleOAuthProvider>
  );
}
